Repository graveflex/mono, pull requests merged in 2024-09, with the labels that each got.

#188 fix: render issue with next links
  .github/workflows/deploy-preview.yml
  package.json
  pnpm-lock.yaml
Labels: tests passed

#195 debug(header): performance
  apps/web/src/app/(app)/[locale]/[...slug]/page.tsx
  apps/web/src/app/(app)/[locale]/page.tsx
  apps/web/src/globals/Layout/Layout.client.tsx
  apps/web/src/globals/Layout/Layout.stories.tsx
  apps/web/src/globals/Layout/index.tsx
  packages/ui/components/CtaLink/index.tsx
  packages/ui/components/Header/index.tsx
  packages/ui/components/primitives/PayloadLink/index.tsx
Labels: tests passed

#194 fix(i18n): resolve issues with the next-intl plugin
  apps/web/messages/en-US.json
  apps/web/messages/es-US.json
  apps/web/next-env.d.ts
  apps/web/package.json
  apps/web/src/app/(app)/[locale]/[...slug]/page.tsx
  apps/web/src/app/(app)/[locale]/baseline/layout.tsx
  apps/web/src/app/(app)/[locale]/baseline/with-data/page.tsx
  apps/web/src/app/(app)/[locale]/baseline/without-data/page.tsx
  apps/web/src/app/(app)/[locale]/layout.tsx
  apps/web/src/app/(app)/[locale]/page.tsx
  apps/web/src/app/(app)/[locale]/refract/layout.tsx
  apps/web/src/app/(app)/[locale]/refract/page.client.tsx
  apps/web/src/app/(app)/[locale]/refract/providers.tsx
  apps/web/src/app/(app)/[locale]/refract/with-data/page.tsx
  apps/web/src/app/(app)/[locale]/refract/with-theme-and-data-and-image/page.tsx
  apps/web/src/app/(app)/[locale]/refract/with-theme-and-data/page.tsx
  apps/web/src/app/(app)/[locale]/refract/with-theme-no-data/page.tsx
  apps/web/src/app/(app)/[locale]/refract/without-data/page.tsx
  apps/web/src/app/(app)/[locale]/styled/layout.tsx
  apps/web/src/app/(app)/[locale]/styled/page.client.tsx
  apps/web/src/app/(app)/[locale]/styled/with-data/page.tsx
  apps/web/src/app/(app)/[locale]/styled/without-data/page.tsx
  apps/web/src/globals/Layout/Layout.client.tsx
  apps/web/src/globals/Layout/Layout.stories.tsx
  apps/web/src/i18n.ts
  apps/web/src/i18n/request.ts
  apps/web/src/i18n/routing.ts
  apps/web/src/middleware.ts
  apps/web/src/middleware.ts.bk
  package.json
  pnpm-lock.yaml
Labels: tests passed

#196 fix(blog): Re-add blog and separate data fetching.
  apps/web/src/app/(app)/[locale]/(blog)/blog/[...slug]/page.client.tsx
  apps/web/src/app/(app)/[locale]/(blog)/blog/[...slug]/page.tsx
  apps/web/src/app/(app)/[locale]/(blog)/blog/components/posts.tsx
  apps/web/src/app/(app)/[locale]/(blog)/blog/page.client.tsx
  apps/web/src/app/(app)/[locale]/(blog)/blog/page.tsx
  packages/ui/components/GeneralCard/index.tsx
Labels: tests passed

#198 feat(add): draft dir struct
  .env.debug
  .github/workflows/build.yaml
  .github/workflows/deploy-preview.yml
  .github/workflows/deploy-production.yml
  apps/web/next.config.mjs
  apps/web/package.json
  apps/web/payload.config.ts
  apps/web/src/app/(app)/[locale]/(blog)/blog/[...slug]/page.tsx
  apps/web/src/app/(app)/[locale]/(blog)/blog/page.tsx
  apps/web/src/app/(app)/[locale]/[...slug]/page.tsx
  apps/web/src/app/(app)/[locale]/draft/(blog)/blog/[...slug]/page.tsx
  apps/web/src/app/(app)/[locale]/draft/(blog)/blog/page.tsx
  apps/web/src/app/(app)/[locale]/draft/[...slug]/page.tsx
  apps/web/src/app/(app)/[locale]/draft/layout.tsx
  apps/web/src/app/(app)/[locale]/draft/page.tsx
  apps/web/src/app/(app)/[locale]/layout.tsx
  apps/web/src/app/(app)/[locale]/page.tsx
  apps/web/src/blocks/FullBleedImageBlock/FullBleedImageBlock.config.ts
  apps/web/src/blocks/SectionHeaderBlock/SectionHeaderBlock.config.ts
  apps/web/src/collections/Pages.ts
  apps/web/src/components/RefreshRouteOnSave.tsx
  apps/web/src/globals/BlogIndex/BlogIndex.config.ts
  apps/web/src/globals/Home/Homepage.config.ts
  apps/web/src/globals/Layout/Layout.stories.tsx
  apps/web/src/lib/constants.ts
  apps/web/src/migrations/20240830_235657.json
  apps/web/src/migrations/20240830_235657.ts
  apps/web/src/migrations/20240906_190653.json
  apps/web/src/migrations/20240906_190653.ts
  apps/web/src/migrations/index.ts
  package.json
  turbo.json
Labels: tests passed

#200 fix(four-oh-four): Missing content & layout.
  apps/web/messages/en-US.json
  apps/web/messages/es-US.json
  apps/web/src/app/(app)/[locale]/(blog)/blog/[...slug]/page.tsx
  apps/web/src/app/(app)/[locale]/(blog)/blog/page.tsx
  apps/web/src/app/(app)/[locale]/[...slug]/page.tsx
  apps/web/src/app/(app)/[locale]/draft/layout.tsx
  apps/web/src/app/(app)/[locale]/layout.tsx
  apps/web/src/app/(app)/[locale]/not-found.tsx
  apps/web/src/app/(app)/[locale]/page.tsx
  apps/web/src/components/RefreshRouteOnSave.tsx
  apps/web/src/components/UpdatePageTheme.tsx
  apps/web/src/globals/FourOhFour/FourOhFour.client.tsx
  apps/web/src/globals/Layout/Layout.client.tsx
  apps/web/src/globals/Layout/index.tsx
  apps/web/src/lib/StyledComponentRegistry.tsx
  biome.json
  packages/theme/src/Reset.tsx
  packages/theme/src/ThemeProvider.tsx
  packages/ui/components/BlogIndex/index.tsx
  packages/ui/components/GeneralCard/index.tsx
Labels: tests passed, ready for review

#199 fix(ResponsivePayloadImage): reduce loading / rendering time
  .github/workflows/deploy-preview.yml
  apps/web/src/app/(app)/[locale]/baseline/layout.tsx
  apps/web/src/app/(app)/[locale]/refract/layout.tsx
  apps/web/src/app/(app)/[locale]/refract/page.client.tsx
  apps/web/src/app/(app)/[locale]/refract/with-dynamic-import/page.tsx
  apps/web/src/app/(app)/[locale]/refract/with-header/page.tsx
  apps/web/src/app/(app)/[locale]/refract/with-layout-no-header/page.tsx
  apps/web/src/app/(app)/[locale]/refract/with-theme-and-data-and-payload-image/page.tsx
  apps/web/src/app/(app)/[locale]/styled/layout.tsx
  apps/web/src/blocks/CardGridBlock/CardGridBlock.stories.tsx
  apps/web/src/blocks/FullBleedImageBlock/FullBleedImageBlock.stories.tsx
  apps/web/src/blocks/GalleryGridBlock/GalleryGridBlock.stories.tsx
  apps/web/src/blocks/HeroBlock/HeroBlock.stories.tsx
  apps/web/src/blocks/HeroBlock/index.tsx
  apps/web/src/blocks/TextImageBlock/TextImageBlock.stories.tsx
  apps/web/src/blocks/TextImageBlock/index.tsx
  apps/web/src/collections/Images.ts
  apps/web/src/globals/Layout/Layout.client.tsx
  apps/web/src/globals/Layout/index.tsx
  apps/web/src/migrations/20240906_190653.ts
  apps/web/src/migrations/20240906_234551.json
  apps/web/src/migrations/20240909_211129.json
  apps/web/src/migrations/20240909_211129.ts
  apps/web/src/migrations/index.ts
  packages/types/payload-types.ts
  packages/ui/components/BlogDetail/index.tsx
  packages/ui/components/BlogIndex/index.tsx
  packages/ui/components/GeneralCard/GeneralCard.stories.tsx
  packages/ui/components/GeneralCard/index.tsx
  packages/ui/components/Header/index.tsx
  packages/ui/components/primitives/ResponsivePayloadImage/ResponsivePayloadImage.stories.tsx
  packages/ui/components/primitives/ResponsivePayloadImage/index.tsx
  packages/ui/utils/multipleImages.ts
Labels: tests passed

#201 fix(styles): Layout and styles.
  apps/web/next-env.d.ts
  packages/ui/components/CtaButton/index.tsx
Labels: tests passed

#197 Feat/invalidate cache hook
  apps/web/payload.config.ts
  apps/web/src/app/(app)/[locale]/(blog)/blog/[...slug]/page.tsx
  apps/web/src/app/(app)/[locale]/(blog)/blog/page.tsx
  apps/web/src/app/(app)/[locale]/[...slug]/page.tsx
  apps/web/src/app/(app)/[locale]/page.tsx
  apps/web/src/collections/Tags.ts
  apps/web/src/globals/FourOhFour/FourOhFour.config.ts
  apps/web/src/globals/Layout/Layout.config.ts
  apps/web/src/globals/Layout/index.tsx
  apps/web/src/hooks/globalInvalidateCache.ts
  apps/web/src/hooks/invalidateCache.ts
Labels: enhancement, tests passed, ready for review

#203 fix(ci): lint
  apps/web/payload.config.ts
Labels: tests passed
