Repository graveflex/mono, pull requests merged in 2024-08, with the labels that each got.

#150 feat(add): blocks transfer
  apps/web/src/app/(app)/[locale]/[[...slug]]/page.tsx
  apps/web/src/blocks/FullBleedImageBlock/FullBleedImageBlock.config.ts
  apps/web/src/blocks/FullBleedImageBlock/FullBleedImageBlock.stories.tsx
  apps/web/src/blocks/FullBleedImageBlock/__tests__/index.test.tsx
  apps/web/src/blocks/FullBleedImageBlock/index.tsx
  apps/web/src/blocks/IframeBlock/IframeBlock.config.ts
  apps/web/src/blocks/IframeBlock/IframeBlock.stories.tsx
  apps/web/src/blocks/IframeBlock/__tests__/index.test.tsx
  apps/web/src/blocks/IframeBlock/index.tsx
  apps/web/src/collections/Pages.ts
  apps/web/src/components/BlocksRenderer/index.tsx
  apps/web/src/lib/fetchPayloadDataRest.ts
  apps/web/src/migrations/20240807_155837.json
  apps/web/src/migrations/20240807_155837.ts
  packages/types/payload-types.ts
Labels: tests passed

#151 Feat/component modal + dep updates
  apps/web/src/app/(app)/[locale]/[[...slug]]/page.tsx
  apps/web/src/blocks/HeroBlock/index.tsx
  apps/web/src/payload/fields/Modal.ts
  package.json
  packages/theme/src/light.ts
  packages/types/payload-types.ts
  packages/ui/components/Modal/Modal.stories.tsx
  packages/ui/components/Modal/__tests__/index.test.tsx
  packages/ui/components/Modal/index.tsx
  packages/ui/icons/stories/util/IconStoryWrapper.tsx
  pnpm-lock.yaml
Labels: tests passed

#152 Feat/seo plugin + video embed
  apps/web/package.json
  apps/web/payload.config.ts
  apps/web/src/app/(app)/[locale]/(blog)/blog/[...slug]/page.tsx
  apps/web/src/app/(app)/[locale]/(blog)/blog/page.tsx
  apps/web/src/app/(app)/[locale]/[[...slug]]/page.tsx
  apps/web/src/blocks/VideoBlock/VideoBlock.config.ts
  apps/web/src/blocks/VideoBlock/index.tsx
  apps/web/src/collections/Pages.ts
  apps/web/src/collections/Posts.ts
  apps/web/src/migrations/20240812_173039.json
  apps/web/src/migrations/20240812_173039.ts
  package.json
  packages/types/payload-types.ts
  packages/ui/components/Video/PlayButton.tsx
  packages/ui/components/Video/index.tsx
  pnpm-lock.yaml
Labels: tests passed, migrations, block, component, CMS

#153 fix(payload-config): nodemailer err + sharp
  apps/web/payload.config.ts
  package.json
  packages/settings/index.ts
  pnpm-lock.yaml
Labels: tests passed

#133 Feat/seed kitchen-sink refactor DCH-59
  _templates/block/new/Block.config.ejs.t
  _templates/block/new/Block.stroies.ejs.t
  _templates/block/new/BlockSeed.ejs.t
  _templates/block/new/KitchenSinkAssign.ejs.t
  _templates/block/new/KitchenSinkImport.ejs.t
  _templates/block/new/KitchenSinkResolve.ejs.t
  _templates/block/new/index.ejs.t
  _templates/block/new/prompt.js
  apps/web/bin/seed_images.ts
  apps/web/bin/seed_kitchen-sink.ts
  apps/web/src/blocks/CardGridBlock/CardGridBlockSeed.ts
  apps/web/src/blocks/FAQBlock/FAQBlockSeed.ts
  apps/web/src/blocks/GalleryGridBlock/GalleryGridBlockSeed.ts
  apps/web/src/blocks/HeroBlock/HeroBlockSeed.ts
  apps/web/src/blocks/IconGridBlock/IconGridSeed.ts
  apps/web/src/blocks/IframeBlock/iframeSeed.ts
  apps/web/src/blocks/MarkdownBlock/MarkdownBlockSeed.ts
  apps/web/src/blocks/SectionHeaderBlock/SectionHeaderSeed.ts
  apps/web/src/blocks/TextImageBlock/TextImageBlockSeed.ts
  package.json
  packages/ui/package.json
  pnpm-lock.yaml
Labels: enhancement, tests passed, ready for review

#165 deps(upgade): payload v78 -> v90
  apps/web/bin/seed-nav.ts
  apps/web/bin/seed_blog.ts
  apps/web/bin/seed_images.ts
  apps/web/bin/seed_kitchen-sink.ts
  apps/web/package.json
  apps/web/payload.config.ts
  apps/web/src/app/(payload)/admin/[[...segments]]/not-found.tsx
  apps/web/src/app/(payload)/admin/[[...segments]]/page.tsx
  apps/web/src/app/(payload)/admin/importMap.js
  apps/web/src/app/(payload)/layout.tsx
  apps/web/src/components/AdminRowLabel/index.tsx
  apps/web/src/globals/Layout/Layout.config.ts
  apps/web/src/migrations/20240801_211332.json
  apps/web/src/migrations/20240801_211332.ts
  apps/web/src/migrations/20240802_195000.json
  apps/web/src/migrations/20240802_195000.ts
  apps/web/src/migrations/20240807_155837.ts
  apps/web/src/migrations/20240812_173039.json
  apps/web/src/migrations/20240812_173039.ts
  apps/web/src/migrations/20240822_174406.json
  apps/web/src/migrations/20240822_174406.ts
  apps/web/src/migrations/index.ts
  package.json
  packages/types/payload-types.ts
  pnpm-lock.yaml
Labels: tests passed

#166 Feat(performance): image op / loading suspense / sitemap
  apps/web/next.config.mjs
  apps/web/package.json
  apps/web/src/app/(app)/[locale]/[[...slug]]/page.client.tsx
  apps/web/src/app/sitemap.ts
  apps/web/src/components/Loading/index.tsx
  packages/ui/components/primitives/ResponsivePayloadImage/index.tsx
  packages/ui/package.json
  pnpm-lock.yaml
Labels: tests passed, ready for review

#168 feat(lighthouse): blocks: update image container sizes
  apps/web/src/app/(app)/[locale]/(blog)/blog/[...slug]/page.tsx
  apps/web/src/app/(app)/[locale]/(blog)/blog/page.tsx
  apps/web/src/blocks/GalleryGridBlock/index.tsx
  apps/web/src/blocks/HeroBlock/index.tsx
  apps/web/src/blocks/IconGridBlock/index.tsx
  apps/web/src/blocks/TextImageBlock/index.tsx
  packages/ui/components/GeneralCard/index.tsx
Labels: tests passed

#171 feat: Add `dotenvx` and configuration
  .env
  .env.ci
  .env.example
  .env.test
  .github/workflows/lint-and-test.yaml
  .gitignore
  .vercelignore
  apps/web/bin/seed-nav.ts
  apps/web/bin/seed_blog.ts
  apps/web/bin/seed_images.ts
  apps/web/bin/seed_kitchen-sink.ts
  apps/web/package.json
  apps/web/payload.config.ts
  apps/web/setup.ts
  apps/web/src/blocks/FormBlock/index.tsx
  apps/web/src/blocks/HeroBlock/index.tsx
  apps/web/src/blocks/TextImageBlock/index.tsx
  apps/web/src/payload/payloadClient.ts
  package.json
  packages/settings/package.json
  packages/settings/vite.config.ts
  packages/settings/vite.config.ts.timestamp-1713739591437-0067ff8c3263d.mjs
  packages/settings/vite.config.ts.timestamp-1717100919744-430bf1f4e1a6d.mjs
  packages/settings/vite.config.ts.timestamp-1717101339169-8c5326b9cf6f8.mjs
  packages/ui/components/Header/index.tsx
  packages/ui/package.json
  packages/ui/setup.ts
  pnpm-lock.yaml
Labels: tests passed

#175 feat: use localAPI for all server-side data fetching
  .env
  apps/web/next.config.mjs
  apps/web/package.json
  apps/web/payload.config.ts
  apps/web/src/app/(app)/[locale]/(blog)/blog/[...slug]/page.tsx
  apps/web/src/app/(app)/[locale]/(blog)/blog/page.tsx
  apps/web/src/app/(app)/[locale]/[[...slug]]/page.tsx
  apps/web/src/app/(app)/[locale]/error.tsx
  apps/web/src/app/(app)/[locale]/layout.tsx
  apps/web/src/app/(app)/[locale]/not-found.tsx
  apps/web/src/app/sitemap.ts
  package.json
  pnpm-lock.yaml
Labels: tests passed

#181 fix: enables `disablePayloadAccessControl` for images and videos with vercel blob storage
  apps/web/payload.config.ts
Labels: tests passed

#182 feat(Header): refresh from ukandu updates
  apps/web/src/globals/Layout/index.tsx
  packages/ui/components/Header/index.tsx
Labels: tests passed

#183 fix(next.config): disable react complier + use refract
  apps/web/next.config.mjs
  apps/web/src/blocks/FullBleedImageBlock/index.tsx
  apps/web/src/blocks/VideoBlock/index.tsx
  packages/ui/components/CtaLink/index.tsx
  packages/ui/components/Pagination/index.tsx
  packages/ui/icons/stories/util/IconStoryWrapper.tsx
Labels: tests passed
