Repository graveflex/mono, pull requests merged in 2024-04, with the labels that each got.

#74 Feat(component): icon components
  _templates/icon/new/Icon.ejs.t
  _templates/icon/new/IconSelect.ejs.t
  _templates/icon/new/index.ejs.t
  _templates/icon/new/prompt.js
  apps/web/next-env.d.ts
  apps/web/next.config.js
  apps/web/package.json
  apps/web/src/payload/fields/IconSelect.ts
  package.json
  packages/ui/components/RenderIcon/RenderIcon.stories.tsx
  packages/ui/components/RenderIcon/__tests__/index.test.tsx
  packages/ui/components/RenderIcon/index.tsx
  packages/ui/icons/__tests__/index.test.tsx
  packages/ui/icons/core/ArrowDown.tsx
  packages/ui/icons/core/ArrowLeft.tsx
  packages/ui/icons/core/ArrowNesting.tsx
  packages/ui/icons/core/ArrowRight.tsx
  packages/ui/icons/core/ArrowUp.tsx
  packages/ui/icons/core/CaretDown.tsx
  packages/ui/icons/core/CaretLeft.tsx
  packages/ui/icons/core/CaretRight.tsx
  packages/ui/icons/core/CaretUp.tsx
  packages/ui/icons/core/Check.tsx
  packages/ui/icons/core/Close.tsx
  packages/ui/icons/core/DoubleCaretDown.tsx
  packages/ui/icons/core/DoubleCaretLeft.tsx
  packages/ui/icons/core/DoubleCaretRight.tsx
  packages/ui/icons/core/DoubleCaretUp.tsx
  packages/ui/icons/core/Error.tsx
  packages/ui/icons/core/LinkOut.tsx
  packages/ui/icons/core/MinusSign.tsx
  packages/ui/icons/core/Person.tsx
  packages/ui/icons/core/PlusSign.tsx
  packages/ui/icons/core/Quote.tsx
  packages/ui/icons/core/Search.tsx
  packages/ui/icons/core/SolidArrowDown.tsx
  packages/ui/icons/core/SolidArrowLeft.tsx
  packages/ui/icons/core/SolidArrowRight.tsx
  packages/ui/icons/core/SolidArrowUp.tsx
  packages/ui/icons/core/index.tsx
  packages/ui/icons/stories/Core.stories.tsx
  packages/ui/icons/stories/util/IconStoryWrapper.tsx
  packages/ui/icons/svgr.d.ts
  packages/ui/package.json
  yarn.lock
Labels: tests passed, ready for review

#76 Feat/block wrapper
  apps/docs/.storybook/main.ts
  apps/docs/tsconfig.json
  apps/web/tsconfig.tsbuildinfo
  packages/ui/components/Wrapper/Wrapper.stories.tsx
  packages/ui/components/Wrapper/__tests__/Wrapper.test.tsx
  packages/ui/components/Wrapper/index.tsx
  packages/ui/package.json
Labels: tests passed

#75 feat(payload): draft preview ECF-96
  apps/web/src/app/(app)/[[...slug]]/page.tsx
  apps/web/src/collections/Pages.ts
  apps/web/src/lib/fetchPayloadDataRest.ts
Labels: ready for review

#77 hotFix(icons): storybook defaults
  packages/ui/components/RenderIcon/RenderIcon.stories.tsx
  packages/ui/components/RenderIcon/index.tsx
Labels: tests passed, ready for review

#79 feat(update): flatten pageConfig
  apps/web/payload.config.ts
  apps/web/src/app/(app)/[[...slug]]/page.client.tsx
  apps/web/src/app/(app)/[[...slug]]/page.tsx
  apps/web/src/collections/Pages.ts
  apps/web/src/migrations/20240403_183958.json
  apps/web/src/migrations/20240403_183958.ts
  apps/web/src/payload/utils/formatSlug.ts
  apps/web/tsconfig.tsbuildinfo
  packages/types/payload-types.ts
Labels: tests passed, ready for review

#88 hotFix(previews): update path to include /slug
  apps/web/payload.config.ts
  apps/web/src/collections/Pages.ts
Labels: tests passed

#93 feat(remove): pageConfig ref
  apps/web/src/hooks/publishBeforeRead.ts
Labels: tests passed, ready for review
